version: "3"
services:

  nginx:
    image: nginx
    ports:
    - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
    - /home/centos/nginx.conf:/etc/nginx/nginx.conf:ro
    - /home/centos/html:/usr/share/nginx/html:ro

  api:
    image: fn-tec.com/mine:1.0.0
    ports:
    - "8080:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure